<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**" />
    <Compile Remove="TempViGemInspect\**" />
    <EmbeddedResource Remove="Tests\**" />
    <EmbeddedResource Remove="TempViGemInspect\**" />
    <None Remove="Tests\**" />
    <None Remove="TempViGemInspect\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Nefarius.ViGEm.Client" Version="1.21.256" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png" />
  </ItemGroup>

</Project>
